# Generated by Django 5.1.2 on 2024-10-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20241029_0113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionWithAnswer',
        ),
    ]
