# Generated by Django 5.1.2 on 2024-10-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_question_questionwithanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionwithanswer',
            name='reponse_correcte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Réponse correcte'),
        ),
    ]
