# Generated by Django 5.1.2 on 2024-10-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='startname',
            new_name='username',
        ),
    ]
