# Generated by Django 5.1.2 on 2024-10-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/'),
        ),
    ]
