# Generated by Django 5.1.2 on 2024-10-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
