# Generated by Django 5.1.2 on 2024-10-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_education_customuser_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
